site_name: Elliptic curve cryptography stuff
site_description: 'Attacks and challenges on ECC'

repo_url: https://github.com/kabachook/ecc
repo_name: "kabachook/ecc"

theme:
  name: 'material'
  icon:
    logo: fontawesome/solid/infinity
  palette:
    primary: 'deep purple'
    accent: 'purple'
  custom_dir: theme/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js'
  - 'static/tex.js'
extra_css:
  - 'static/style.css'

docs_dir: ecc
edit_uri: blob/master/ecc/

nav:
  - Home: 'README.md'
  - Theory:
    - Base: 'theory/base.md'
    - Pairings: 'theory/pairings.md'
  - Tasks:
    - 'Anomalous curves': 'tasks/anomalous/README.md'
    - 'Curves with smooth-number order': 'tasks/pohlig-hellman/README.md'
    - 'Chain of fools/CurveBall attack': 'tasks/chain-of-fools/README.md'
    - 'Singular curves': 'tasks/singular/README.md'
  - TODO: 'TODO.md'
